[package]
name = "squelch"
description = "Making things shut up since 2024"
license = "MIT"
homepage = "https://github.com/xrl/squelch"
repository = "https://github.com/xrl/squelch"
version = "0.1.0"
edition = "2021"

[dependencies]
